# Solo audio configuration
--extract-audio 
--prefer-ffmpeg
--audio-format mp3
--audio-quality 4
--add-metadata


# do not copy the mtime
--no-mtime

# output



# resume list
--download-archive audio.txt 